name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull shanoof/abacus:latest
      - name: Delete old dokcer container
        run: sudo docker rm -f abacus-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name abacus-container shanoof/abacus:latest
